web:
  container_name: polyplot
  build: .
  volumes:
   - .:/root
  ports:
   - 5000:5000
  links:
   - database

notebook:
  container_name: jupyter
  image: jupyter/minimal-notebook:latest
  ports:
   - 8888:8888
  links:
   - database

database:
  container_name: mongo
  image: mongo:3.0.2
  ports:
   - 27017:27017
