web:
  build: .
  container_name: iGraph
  command: python3 app/root.py
  ports:
   - 5000:5000
  volumes:
   - .:/root
  links:
    - mongo

mongo:
  container_name: iMongo
  image: mongo:3.0.2
  ports:
    - 27017:27017
