web:
  build: .
  command: python3 app/root.py
  ports:
   - 5000:5000
  volumes:
   - .:/root
  links:
    - mongo

notebook:
  image: jupyter/minimal-notebook
  ports:
    - 8888:8888
  links:
    - mongo

mongo:
  image: mongo:3.0.2
  ports:
    - 27017:27017
